name: unit testing
on:
  push:
    branches: 
     - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: npm i react-scripts
      - run: npm run test